AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy guardian streamliner lambda function for publishing to SQS

Parameters:
  GuardianApiKey:
    Type: String
    Description: Guardian API Key
    NoEcho: true
  
  MessageRetentionPeriod:
    Type: Number
    Default: 259200  # 3 days in seconds
    Description: SQS message retention period in seconds (default 3 days per requirements)

Resources:
  GuardianSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: guardian-content # name of SQS que
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      VisibilityTimeout: 600

  GSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: articlePublisher
      Runtime: python3.11
      Handler: app.lambda_handler
      CodeUri: ./src
      Timeout: 60
      Environment:
        Variables:
          GUARDIAN_API_KEY: !Ref GuardianApiKey
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:GetQueueUrl
              Resource: !GetAtt GuardianSQSQueue.Arn

Outputs:
  LambdaFunctionArn:
    Description: arn of lambda func
    Value: !GetAtt GSLambdaFunction.Arn

  SQSQueueURL:
    Description: SQS queue url
    Value: !Ref GuardianSQSQueue
